swagger: '2.0'
info:
  description: This is the API exposed by DUE-VDC
  version: 1.0.0
  title: DUE-VDC API
  # put the contact info for your development or API team
  contact:
    email: cataldo.calo@gmail.com

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

# tags are used for organizing operations
tags:
- name: availability
  description: Compute availability of methods

paths:
  /availability/time/{delta_time}:
    get:
      tags:
      - availability
      summary: Get availability of all methods in the last {delta_time} minutes
      produces:
      - application/json
      parameters:
      - in: path
        name: delta_time
        required: true
        type: integer
        x-example: 30
      responses:
        200:
          description: search results matching criteria
          schema:
            type: array
            items:
              $ref: '#/definitions/MetricEntry'
        400:
          description: bad input parameter
        404:
          description: Not Found
  /availability/{method_id}/time/{delta_time}:
    get:
      tags:
      - availability
      summary: Get availability of method with ID {method_id} in the last
              {delta_time} minutes
      produces:
      - application/json
      parameters:
      - in: path
        name: method_id
        required: true
        type: string
        x-example: getAllValuesForBloodTestComponent
      - in: path
        name: delta_time
        required: true
        type: integer
        x-example: 30
      responses:
        200:
          description: search results matching criteria
          schema:
            $ref: '#/definitions/MetricEntry'
        400:
          description: bad input parameter
        404:
          description: Not Found
definitions:
  MetricEntry:
    type: object
    required:
    - method
    - BluePrint-ID
    - value
    - metric
    - unit
    - "@timestamp"
    - delta
    - delta_unit
    - hits
    properties:
      method:
        type: string
        example: getAllValuesForBloodTestComponent
      BluePrint-ID:
        type: string
        example: fakebp
      value:
        type: number
        format: float
        example: 80
      metric:
        type: string
        example: availability
      unit:
        type: string
        example: percentage
      "@timestamp":
        type: string
        format: date-time
        example: 2016-08-29T09:12:33.001+02:00
      delta:
        type: number
        format: float
        example: 30
      delta_unit:
        type: string
        example: minutes
      hits:
        type: integer
        example: 173

# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /caloc/DUE-VDC/1.0.0
schemes:
 - https